
const express = require("express");
const multer = require("multer");
const getter = require("./getandpostcontroller");
const helper = require("./Appointmentcontroller");
const router = express.Router();
router.route("/report").get(getter.getreport);
router.route("/postreport").post(helper.postreport);
router.route("/verify_hospital").get(getter.verify_hospital);
router.route("/all_appointments").get(getter.all_appointments);
router.route("/postverify_hospital").post(getter.postverify_hospital);
router.route("/doctordetails").post(helper.postdoctordetails);
router.route("/profile_doctor").get(helper.getprofiledoctor);
router.route("/rescheduleappointment").get(helper.getrescheduleappointment);
router.route("/confirmappointment").get(helper.getconfirmappointment);
router.route("/Add_schedule").post(helper.postaddschedule);
router.route("/Add_schedule").get(helper.getaddschedule);
router.route("/postsettings").post(helper.postsettings);
router.route("/user_profile").post(helper.postprofile);
router.route("/user_settings").get(helper.getsettings);
router.route("/user_profile").get(helper.getprofile);
// router.route("/schedules/api").get(helper.getscheduleapi);
router.route("/schedule").get(helper.getschedule);
router.route("/bookappointment").get(helper.getbookappointment);
router.route("/bookappointment").post(helper.postbookappointment);
router.route("/").get(getter.indexfile);
router.route("/Login").get(getter.getlogin);
router.route("/SignUp").get(getter.getsignup);
router.route("/Signup").post(getter.postsignup);
router.route("/Login").post(getter.postlogin);
router.route("/MobileNumber").get(getter.getMobileNumber);
router.route("/MobileNumber").post(getter.postMobileNumber);
router.route("/check").post(getter.verifyotp);
router.route("/Doctorlist/:pageno").get(getter.Doctorlist);
router.route("/Dentistry").get(getter.Dentistry);
router.route("/Hospitallist").get(getter.Hospitallist);
router.route("/Forgetpassword").post(getter.getpasspage);
router.route("/forgetpass").post(getter.confirm);
router.route("/forgetpass").get(getter.forgetpass);
router.route("/Mobileforpass").get(getter.Mobileforpass);
router.route("/checkforpass").get(getter.checkforpass);
router.route("/Mobileforpass").post(getter.postMobileforpass);
router.route("/checkforpass").post(getter.postcheckforpass);
router.route("/FAQ").get(getter.getfaq);
router.route("/about-hospital").get(getter.getabouthospital);
router.route("/search").post(getter.search);
router.route("/about_us").get(getter.getabout_us);
router.route("/ContactUs").get(getter.getContactUs);
router.route("/doctor's-profile").get(getter.getdoctorprofile);
router.route("/Appointment").get(getter.getAppointment);
router.route("/travastra-plus").get(getter.getplus);
router.route("/submitquery").get(getter.getsubmitquery);
router.route("/Logout").get(getter.Logout);
router.route("/posteditschedule").post(helper.posteditschedule);
router.route("/showdocuments").get(getter.getdocuments);
// router.route("/Doctorlist/page2").get(getter.page2);
router.route("/img").get(getter.getimg);
router.route("/doctors/getapi").get(getter.getapi);
router.route("/admin_users").get(getter.getadmin_users);
router.route("/admin_hospitals").get(getter.getadmin_hospitals);
router.route("/admin_doctors").get(getter.getadmin_doctors);
router.route("/admin_dashboard/:pageno","admin_dashboard.html").get(getter.getadmin_dashboard);
router.route("/admin_settings").get(getter.getadmin_settings);
router.route("/admin_appointments").get(getter.getadmin_appointments);
router.route("/admin_report").get(getter.getadmin_report);
router.route("/admin_profile").get(getter.getadmin_profile);
module.exports= router;